### ISSUE TITLE
ideas for modules

### ISSUE THREAD

**Issue by stoeffel** [futurize/meta#2]
- [x] fork - pointfree fork `fork(reject, resolve)(future)` => [fork-future](https://github.com/futurize/fork-future)
- [ ] map-future - `mapF(future, [1, 2, 3])` returns a future and runs future for every entry in parallel

**Comment by davidchase** [comment]
Are you going to be including a fl compat implementation of futures in this org?

**Comment by stoeffel** [comment]
Don't know yet. Would be nice to learn more about the internals of `Futures`. Currently data.task is my go to future.
Are you interested in start such a implementation under futurize?

**Comment by stoeffel** [comment]
I mainly planned to add educational stuff about futures and helper modules such as futurize or parallel-future.

**Comment by stoeffel** [comment]
btw. I love your new avatar :bear:

**Comment by davidchase** [comment]
ahh make sense... hmm why limit to futures then? lol maybe more education stuff about other _monads_ like readers, IO, etc

**Comment by davidchase** [comment]
haha.. i feel like i should just do my face instead of avatars...

**Comment by stoeffel** [comment]
> why limit to futures then

I want limit this org to just futures if there is a need for other stuff. We need a better name for it :-)

Futures are just the thing I use a lot lately and there is not much tooling there yet. Like for promises and callbacks there is a lot (f.e. async).

**Comment by stoeffel** [comment]
btw. my initial plan with `futurize` was to create tools like [async](https://github.com/caolan/async) for `Futures`.

**Comment by davidchase** [comment]
gotcha... its a nice tool `async` just big but thats a good idea for `Futures`

btw did think of other names?

**Comment by stoeffel** [comment]
> btw did think of other names?

nothing good yet:
- zukunft (german for future)
- back-to-future
- back-to-the-future
- fantastic-future
- fantasy-future

**Comment by davidchase** [comment]
futurology - the study of futures... LOL

**Comment by stoeffel** [comment]
futurology :rocket:
